# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Mateo Atwi
email: mateoatwi@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  This website is here for me to summarize and collect all that I've done and worked on. Enjoy!
baseurl: "" # the subpath of your site, e.g. /blog
url: mateoatwi.com # the base hostname & protocol for your site, e.g. http://example.com
github_username:  MateoAtwi

# Build settings
markdown: kramdown
# use rouge to highlight the code
highlighter: rouge

#theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag


#ended up handling this with a line inside the blog.html
#excerpt identifier:
#excerpt_separator:
#  - <br />

#collections:
#  authors:
#  

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude: [Tutorial/minima-2.5.0]
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
#   - Tutorial/minima-2.5.0
